ifeq ($(TARGET_BOARD_PLATFORM),holi)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),lahaina)
ENABLE_SECCAM_2_0 := true
ENABLE_TRUSTED_UI_2_0 := true
ENABLE_TRUSTED_UI_VM_3_0 := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
ENABLE_WIDEVINE_LOAD_LICENSE := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),kona)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),lito)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
APP_BUFFER_CFLAGS := -DAPP_BUF_ALIGNMENT=0x1000

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OTA_PROVISIONING := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),bengal)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ifeq ($(TARGET_BOARD_PLATFORM),bengal_32)
ENABLE_WIDEVINE_OEMCRYPTO := false
else
ENABLE_WIDEVINE_OEMCRYPTO := true
endif
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),monaco)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif


ifeq ($(TARGET_BOARD_PLATFORM),atoll)
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif


ifeq ($(TARGET_BOARD_PLATFORM),msmnile)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#Widevine DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := false
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OTA_PROVISIONING := true

#Playready DRM definitions
ENABLE_PLAYREADY_DRM := true
PLAYREADY_USES_CP_ION_V2 := true
PLAYREADY_SUPPORTS_OPS := true
PLAYREADY_SUPPORTS_LAT := false
endif

ifeq ($(TARGET_BOARD_PLATFORM),sdmshrike)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#Widevine DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true

#Playready DRM definitions
ENABLE_PLAYREADY_DRM := true
PLAYREADY_USES_CP_ION_V2 := true
PLAYREADY_SUPPORTS_OPS := true
PLAYREADY_SUPPORTS_LAT := false

endif

ifeq ($(TARGET_BOARD_PLATFORM),sdm845)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ENABLE_TRUSTED_APP_LOADER := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),$(TRINKET))
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := false
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),$(MSMSTEPPE))
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#Widevine DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := false
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OTA_PROVISIONING := true

#Playready DRM definitions
ENABLE_PLAYREADY_DRM := true
PLAYREADY_USES_CP_ION_V2 := true
PLAYREADY_SUPPORTS_OPS := true
PLAYREADY_SUPPORTS_LAT := false

endif

ifeq ($(TARGET_BOARD_PLATFORM),sdm710)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := false
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
DISABLE_DISPLAY_CLK_VOTING := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),sdm660)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ENABLE_TRUSTED_APP_LOADER := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8998)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ENABLE_TRUSTED_APP_LOADER := true
ST_TARGET_CFLAGS := -DST_TARGET_MSM8998

#DRM definitions
ENABLE_WIDEVINE_DRM := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8996)
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_MSM8996

#DRM definitions
ENABLE_WIDEVINE_DRM := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8937)
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_THORIUM

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8953)
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_MSM8953

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif

#Disable widevine L1 support for GO targets
ifeq ($(TARGET_BOARD_SUFFIX),_32go)
ENABLE_WIDEVINE_OEMCRYPTO := false
endif

#Disable widevine L1 support for GO targets
ifeq (($(TARGET_BOARD_SUFFIX),_go_aon))
ENABLE_WIDEVINE_OEMCRYPTO := false
endif

#Disable widevine L1 support for GO targets
ifeq (($(TARGET_BOARD_SUFFIX),_go))
ENABLE_WIDEVINE_OEMCRYPTO := false
endif

#Disable widevine L1 support for lily targets
ifeq (($(TARGET_BOARD_SUFFIX),_lily))
ENABLE_WIDEVINE_OEMCRYPTO := false
endif
