/*
 * Copyright (c) 2020 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qualcomm_qti_LibsocHelper */

#ifndef _Included_com_qualcomm_qti_LibsocHelper
#define _Included_com_qualcomm_qti_LibsocHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qualcomm_qti_LibsocHelper
 * Method:    native_getSocInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qualcomm_qti_LibsocHelper_native_1getSocInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
