#pragma once
/*
* Copyright (c) 2020 Qualcomm Technologies, Inc.
* All Rights Reserved.
* Confidential and Proprietary - Qualcomm Technologies, Inc.
*/
/** @cond */

// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"
#include "proxy_base.hpp"

class IIAppClient {
   public:
    static const int32_t ERROR_APP_NOT_FOUND = INT32_C(10);
    static const int32_t ERROR_APP_RESTART_FAILED = INT32_C(11);
    static const int32_t ERROR_APP_UNTRUSTED_CLIENT = INT32_C(12);
    static const int32_t ERROR_CLIENT_CRED_PARSING_FAILURE = INT32_C(13);
    static const int32_t ERROR_APP_LOAD_FAILED = INT32_C(14);

    virtual ~IIAppClient() {}

    virtual int32_t getAppObject(const void* appDistName_ptr, size_t appDistName_len, ProxyBase &obj_ref) = 0;

   protected:
    static const ObjectOp OP_getAppObject = 0;
};

class IAppClient : public IIAppClient, public ProxyBase {
   public:
    IAppClient() {}
    IAppClient(Object impl) : ProxyBase(impl) {}
    virtual ~IAppClient() {}

    virtual int32_t getAppObject(const void* appDistName_ptr, size_t appDistName_len, ProxyBase &obj_ref) {
        ObjectArg a[2];
        a[0].bi = (ObjectBufIn) {appDistName_ptr, appDistName_len * 1};

        int32_t result = invoke(OP_getAppObject, a, ObjectCounts_pack(1, 0, 0, 1));
        if (Object_OK != result) { return result; }

        obj_ref.consume(a[1].o);

        return result;
    }

};
