/*
 * Copyright (c) 2020 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"

static const uint32_t CTrustedUIApp_UID = UINT32_C(1234);
int32_t CTrustedUIApp_open(Object *objOut);


