/*
 * Copyright (c) 2020 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"

/** @file  IHLOSListenerCBO.idl */

/**
 * @brief
 * HLOSListenerCBO interface provides methods to communicate to the Trusted UI HAL in HLOS.
 */

/** @cond */

class IHLOSListenerCBO {
   public:
    virtual ~IHLOSListenerCBO() {}

    virtual int32_t onComplete() = 0;
    virtual int32_t onError(int32_t error_val) = 0;
    virtual int32_t handleCmd(const void* cmd_ptr, size_t cmd_len, void* rsp_ptr, size_t rsp_len, size_t* rsp_lenout) = 0;

   protected:
    static const ObjectOp OP_onComplete = 0;
    static const ObjectOp OP_onError = 1;
    static const ObjectOp OP_handleCmd = 2;
};

class HLOSListenerCBO : public IHLOSListenerCBO, ProxyBase {
   public:
    HLOSListenerCBO() = delete;
    HLOSListenerCBO(Object impl) : ProxyBase(impl) {}
    virtual ~HLOSListenerCBO() {}

    virtual int32_t onComplete() {
        return invoke(OP_onComplete, 0, 0);
    }

    virtual int32_t onError(int32_t error_val) {
        ObjectArg a[1];
        a[0].b = (ObjectBuf) {&error_val, sizeof(int32_t)};

        return invoke(OP_onError, a, ObjectCounts_pack(1, 0, 0, 0));
    }

    virtual int32_t handleCmd(const void* cmd_ptr, size_t cmd_len, void* rsp_ptr, size_t rsp_len, size_t* rsp_lenout) {
        ObjectArg a[2];
        a[0].bi = (ObjectBufIn) {cmd_ptr, cmd_len * 1};
        a[1].b = (ObjectBuf) {rsp_ptr, rsp_len * 1};

        int32_t result = invoke(OP_handleCmd, a, ObjectCounts_pack(1, 1, 0, 0));
        if (Object_OK != result) { return result; }

        *rsp_lenout = a[1].b.size / 1;

        return result;
    }

};

