#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"
#include "proxy_base.hpp"

/*===================================================================================
  Copyright (c) 2020 Qualcomm Technologies, Inc.
  All Rights Reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.
  ===================================================================================*/

/*===================================================================================
FILE:  CTouchInput.idl

DESCRIPTION:  This file specifies the UID that is specific to the
TouchInput. And, it is used to register the TouchInput with the
TUI Core Service whenever TouchInput connects to TUI Core Service
using MinkIPC.

=====================================================================================*/

    static const uint32_t CTouchInput_UID = UINT32_C(1);


