/******************************************************************************
#  Copyright (c) 2018-2020 Qualcomm Technologies, Inc.
#  All Rights Reserved.
#  Confidential and Proprietary - Qualcomm Technologies, Inc.
#******************************************************************************/
#include "CallInfo.h"
#include "wireless_data_service_v01.h"

using namespace rildata;

unordered_map<int, DataCallFailCause_t> CallEndReason::mipReasonMap = {
  {WDS_VCER_MIP_FA_REASON_UNSPECIFIED_V01, DataCallFailCause_t::MIP_FA_REASON_UNSPECIFIED},
  {WDS_VCER_MIP_FA_ADMIN_PROHIBITED_V01, DataCallFailCause_t::MIP_FA_ADMIN_PROHIBITED},
  {WDS_VCER_MIP_FA_INSUFFICIENT_RESOURCES_V01, DataCallFailCause_t::MIP_FA_INSUFFICIENT_RESOURCES},
  {WDS_VCER_MIP_FA_MOBILE_NODE_AUTH_FAILURE_V01, DataCallFailCause_t::MIP_FA_MOBILE_NODE_AUTHENTICATION_FAILURE},
  {WDS_VCER_MIP_FA_HA_AUTH_FAILURE_V01, DataCallFailCause_t::MIP_FA_HOME_AGENT_AUTHENTICATION_FAILURE},
  {WDS_VCER_MIP_FA_REQ_LIFETIME_TOO_LONG_V01, DataCallFailCause_t::MIP_FA_REQUESTED_LIFETIME_TOO_LONG},
  {WDS_VCER_MIP_FA_MALFORMED_REQUEST_V01, DataCallFailCause_t::MIP_FA_MALFORMED_REQUEST},
  {WDS_VCER_MIP_FA_MALFOMED_REPLY_V01, DataCallFailCause_t::MIP_FA_MALFORMED_REPLY},
  {WDS_VCER_MIP_FA_ENCAPSULATION_UNAVAILABLE_V01, DataCallFailCause_t::MIP_FA_ENCAPSULATION_UNAVAILABLE},
  {WDS_VCER_MIP_FA_VJHC_UNAVAILABLE_V01, DataCallFailCause_t::MIP_FA_VJ_HEADER_COMPRESSION_UNAVAILABLE},
  {WDS_VCER_MIP_FA_REV_TUNNEL_UNAVAILABLE_V01, DataCallFailCause_t::MIP_FA_REVERSE_TUNNEL_UNAVAILABLE},
  {WDS_VCER_MIP_FA_REV_TUNNEL_IS_MAND_AND_T_BIT_NOT_SET_V01, DataCallFailCause_t::MIP_FA_REVERSE_TUNNEL_IS_MANDATORY},
  {WDS_VCER_MIP_FA_DELIVERY_STYLE_NOT_SUPP_V01, DataCallFailCause_t::MIP_FA_DELIVERY_STYLE_NOT_SUPPORTED},
  {WDS_VCER_MIP_FA_MISSING_NAI_V01, DataCallFailCause_t::MIP_FA_MISSING_NAI},
  {WDS_VCER_MIP_FA_MISSING_HA_V01, DataCallFailCause_t::MIP_FA_MISSING_HOME_AGENT},
  {WDS_VCER_MIP_FA_MISSING_HOME_ADDR_V01, DataCallFailCause_t::MIP_FA_MISSING_HOME_ADDRESS},
  {WDS_VCER_MIP_FA_UNKNOWN_CHALLENGE_V01, DataCallFailCause_t::MIP_FA_UNKNOWN_CHALLENGE},
  {WDS_VCER_MIP_FA_MISSING_CHALLENGE_V01, DataCallFailCause_t::MIP_FA_MISSING_CHALLENGE},
  {WDS_VCER_MIP_FA_STALE_CHALLENGE_V01, DataCallFailCause_t::MIP_FA_STALE_CHALLENGE},
  {WDS_VCER_MIP_HA_REASON_UNSPECIFIED_V01, DataCallFailCause_t::MIP_HA_REASON_UNSPECIFIED},
  {WDS_VCER_MIP_HA_ADMIN_PROHIBITED_V01, DataCallFailCause_t::MIP_HA_ADMIN_PROHIBITED},
  {WDS_VCER_MIP_HA_INSUFFICIENT_RESOURCES_V01, DataCallFailCause_t::MIP_HA_INSUFFICIENT_RESOURCES},
  {WDS_VCER_MIP_HA_MOBILE_NODE_AUTH_FAILURE_V01, DataCallFailCause_t::MIP_HA_MOBILE_NODE_AUTHENTICATION_FAILURE},
  {WDS_VCER_MIP_HA_FA_AUTH_FAILURE_V01, DataCallFailCause_t::MIP_HA_FOREIGN_AGENT_AUTHENTICATION_FAILURE},
  {WDS_VCER_MIP_HA_REGISTRATION_ID_MISMATCH_V01, DataCallFailCause_t::MIP_HA_REGISTRATION_ID_MISMATCH},
  {WDS_VCER_MIP_HA_MALFORMED_REQUEST_V01, DataCallFailCause_t::MIP_HA_MALFORMED_REQUEST},
  {WDS_VCER_MIP_HA_UNKNOWN_HA_ADDR_V01, DataCallFailCause_t::MIP_HA_UNKNOWN_HOME_AGENT_ADDRESS},
  {WDS_VCER_MIP_HA_REV_TUNNEL_UNAVAILABLE_V01, DataCallFailCause_t::MIP_HA_REVERSE_TUNNEL_UNAVAILABLE},
  {WDS_VCER_MIP_HA_REV_TUNNEL_IS_MAND_AND_T_BIT_NOT_SET_V01, DataCallFailCause_t::MIP_HA_REVERSE_TUNNEL_IS_MANDATORY},
  {WDS_VCER_MIP_HA_ENCAPSULATION_UNAVAILABLE_V01, DataCallFailCause_t::MIP_HA_ENCAPSULATION_UNAVAILABLE},
  {WDS_VCER_MIP_HA_REASON_UNKNOWN_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
};

unordered_map<int, DataCallFailCause_t> CallEndReason::internalReasonMap = {
  {WDS_VCER_INTERNAL_CLOSE_IN_PROGRESS_V01, DataCallFailCause_t::CLOSE_IN_PROGRESS},
  {WDS_VCER_INTERNAL_NW_INITIATED_TERMINATION_V01, DataCallFailCause_t::NETWORK_INITIATED_TERMINATION},
  {WDS_VCER_INTERNAL_APP_PREEMPTED_V01, DataCallFailCause_t::MODEM_APP_PREEMPTED},
  {WDS_VCER_INTERNAL_ERR_PDN_IPV4_CALL_DISALLOWED_V01, DataCallFailCause_t::PDN_IPV4_CALL_DISALLOWED},
  {WDS_VCER_INTERNAL_ERR_PDN_IPV4_CALL_THROTTLED_V01, DataCallFailCause_t::PDN_IPV4_CALL_THROTTLED},
  {WDS_VCER_INTERNAL_ERR_PDN_IPV6_CALL_DISALLOWED_V01, DataCallFailCause_t::PDN_IPV6_CALL_DISALLOWED},
  {WDS_VCER_INTERNAL_ERR_PDN_IPV6_CALL_THROTTLED_V01, DataCallFailCause_t::PDN_IPV6_CALL_THROTTLED},
  {WDS_VCER_INTERNAL_MODEM_RESTART_V01, DataCallFailCause_t::MODEM_RESTART},
  {WDS_VCER_INTERNAL_PDP_PPP_NOT_SUPPORTED_V01, DataCallFailCause_t::PDP_PPP_NOT_SUPPORTED},
  {WDS_VCER_INTERNAL_UNPREFERRED_RAT_V01, DataCallFailCause_t::UNPREFERRED_RAT},
  {WDS_VCER_INTERNAL_PHYS_LINK_CLOSE_IN_PROGRESS_V01, DataCallFailCause_t::PHYSICAL_LINK_CLOSE_IN_PROGRESS},
  {WDS_VCER_INTERNAL_APN_PENDING_HANDOVER_V01, DataCallFailCause_t::APN_PENDING_HANDOVER},
  {WDS_VCER_INTERNAL_PROFILE_BEARER_INCOMPATIBLE_V01, DataCallFailCause_t::PROFILE_BEARER_INCOMPATIBLE},
  {WDS_VCER_INTERNAL_MMGSDI_CARD_EVT_V01, DataCallFailCause_t::SIM_CARD_CHANGED},
  {WDS_VCER_INTERNAL_LPM_OR_PWR_DOWN_V01, DataCallFailCause_t::LOW_POWER_MODE_OR_POWERING_DOWN},
  {WDS_VCER_INTERNAL_APN_DISABLED_V01, DataCallFailCause_t::APN_DISABLED},
  {WDS_VCER_INTERNAL_MPIT_EXPIRED_V01, DataCallFailCause_t::MAX_PPP_INACTIVITY_TIMER_EXPIRED},
  {WDS_VCER_INTERNAL_IPV6_ADDR_TRANSFER_FAILED_V01, DataCallFailCause_t::IPV6_ADDRESS_TRANSFER_FAILED},
  {WDS_VCER_INTERNAL_TRAT_SWAP_FAILED_V01, DataCallFailCause_t::TRAT_SWAP_FAILED},
  {WDS_VCER_INTERNAL_INTERNAL_EHRPD_TO_HRPD_FALLBACK_V01, DataCallFailCause_t::EHRPD_TO_HRPD_FALLBACK},
  {WDS_VCER_INTERNAL_MIP_CONFIG_FAILURE_V01, DataCallFailCause_t::MIP_CONFIG_FAILURE},
  {WDS_VCER_INTERNAL_INTERNAL_PDN_INACTIVITY_TIMER_EXPIRED_V01, DataCallFailCause_t::PDN_INACTIVITY_TIMER_EXPIRED},
  {WDS_VCER_INTERNAL_MAX_V4_CONNECTIONS_V01, DataCallFailCause_t::MAX_IPV4_CONNECTIONS},
  {WDS_VCER_INTERNAL_MAX_V6_CONNECTIONS_V01, DataCallFailCause_t::MAX_IPV6_CONNECTIONS},
  {WDS_VCER_INTERNAL_APN_MISMATCH_V01, DataCallFailCause_t::APN_MISMATCH},
  {WDS_VCER_INTERNAL_IP_VERSION_MISMATCH_V01, DataCallFailCause_t::IP_VERSION_MISMATCH},
  {WDS_VCER_INTERNAL_DUN_CALL_DISALLOWED_V01, DataCallFailCause_t::DUN_CALL_DISALLOWED},
  {WDS_VCER_INTERNAL_INTERNAL_EPC_NONEPC_TRANSITION_V01, DataCallFailCause_t::INTERNAL_EPC_NONEPC_TRANSITION},
  {WDS_VCER_INTERNAL_IFACE_IN_USE_V01, DataCallFailCause_t::INTERFACE_IN_USE},
  {WDS_VCER_INTERNAL_APN_DISALLOWED_ON_ROAMING_V01, DataCallFailCause_t::APN_DISALLOWED_ON_ROAMING},
  {WDS_VCER_INTERNAL_APN_PRM_CHG_V01, DataCallFailCause_t::APN_PARAMETERS_CHANGED},
  {WDS_VCER_INTERNAL_NULL_APN_DISALLOWED_V01, DataCallFailCause_t::NULL_APN_DISALLOWED},
  {WDS_VCER_INTERNAL_THERMAL_MITIGATION_V01, DataCallFailCause_t::THERMAL_MITIGATION},
  {WDS_VCER_INTERNAL_DATA_SETTINGS_DISABLED_V01, DataCallFailCause_t::DATA_SETTINGS_DISABLED},
  {WDS_VCER_INTERNAL_DATA_ROAMING_SETTINGS_DISABLED_V01, DataCallFailCause_t::DATA_ROAMING_SETTINGS_DISABLED},
  {WDS_VCER_INTERNAL_DDS_CALL_ABORT_V01, DataCallFailCause_t::DDS_SWITCHED},
  {WDS_VCER_INTERNAL_APN_FORMAT_INVALID_V01, DataCallFailCause_t::FORBIDDEN_APN_NAME},
  {WDS_VCER_INTERNAL_DDS_SWITCH_IN_PROGRESS_V01, DataCallFailCause_t::DDS_SWITCH_IN_PROGRESS},
  {WDS_VCER_INTERNAL_CALL_DISALLOWED_IN_ROAMING_V01, DataCallFailCause_t::CALL_DISALLOWED_IN_ROAMING},
  {WDS_VCER_INTERNAL_NON_IP_NOT_SUPPORTED_V01, DataCallFailCause_t::NON_IP_NOT_SUPPORTED},
  {WDS_VCER_INTERNAL_ERR_PDN_NON_IP_CALL_THROTTLED_V01, DataCallFailCause_t::PDN_NON_IP_CALL_THROTTLED},
  {WDS_VCER_INTERNAL_ERR_PDN_NON_IP_CALL_DISALLOWED_V01, DataCallFailCause_t::PDN_NON_IP_CALL_DISALLOWED},
  {WDS_VCER_INTERNAL_INTERNAL_ERROR_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_CALL_ENDED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_INTERNAL_UNKNOWN_CAUSE_CODE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_UNKNOWN_CAUSE_CODE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_MANDATORY_APN_DISABLED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_INVALID_PROFILE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_INVALID_PROFILE_ID_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_INTERNAL_CALL_ALREADY_PRESENT_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_IP_PDP_MISMATCH_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_IFACE_IN_USE_CFG_MATCH_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_SUBS_ID_MISMATCH_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_VALIDATION_FAILURE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_PROFILES_NOT_COMPATIBLE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_NULL_RESOLVED_APN_NO_MATCH_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_INVALID_APN_NAME_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_INTERNAL_MO_EXCEPTIONAL_NOT_SUPPORTED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
};

unordered_map<int, DataCallFailCause_t> CallEndReason::cmReasonMap = {
  {WDS_VCER_CM_CDMA_LOCK_V01, DataCallFailCause_t::CDMA_LOCK},
  {WDS_VCER_CM_INTERCEPT_V01, DataCallFailCause_t::CDMA_INTERCEPT},
  {WDS_VCER_CM_REORDER_V01, DataCallFailCause_t::CDMA_REORDER},
  {WDS_VCER_CM_REL_SO_REJ_V01, DataCallFailCause_t::CDMA_RELEASE_DUE_TO_SO_REJECTION},
  {WDS_VCER_CM_INCOM_CALL_V01, DataCallFailCause_t::CDMA_INCOMING_CALL},
  {WDS_VCER_CM_ALERT_STOP_V01, DataCallFailCause_t::CDMA_ALERT_STOP},
  {WDS_VCER_CM_ACTIVATION_V01, DataCallFailCause_t::CHANNEL_ACQUISITION_FAILURE},
  {WDS_VCER_CM_MAX_ACCESS_PROBE_V01, DataCallFailCause_t::MAX_ACCESS_PROBE},
  {WDS_VCER_CM_CCS_NOT_SUPP_BY_BS_V01, DataCallFailCause_t::CONCURRENT_SERVICE_NOT_SUPPORTED_BY_BASE_STATION},
  {WDS_VCER_CM_NO_RESPONSE_FROM_BS_V01, DataCallFailCause_t::NO_RESPONSE_FROM_BASE_STATION},
  {WDS_VCER_CM_REJECTED_BY_BS_V01, DataCallFailCause_t::REJECTED_BY_BASE_STATION},
  {WDS_VCER_CM_INCOMPATIBLE_V01, DataCallFailCause_t::CONCURRENT_SERVICES_INCOMPATIBLE},
  {WDS_VCER_CM_NO_CDMA_SRV_V01, DataCallFailCause_t::NO_CDMA_SERVICE},
  {WDS_VCER_CM_UIM_NOT_PRESENT_V01, DataCallFailCause_t::RUIM_NOT_PRESENT},
  {WDS_VCER_CM_RETRY_ORDER_V01, DataCallFailCause_t::CDMA_RETRY_ORDER},
  {WDS_VCER_CM_ACCESS_BLOCK_V01, DataCallFailCause_t::ACCESS_BLOCK},
  {WDS_VCER_CM_ACCESS_BLOCK_ALL_V01, DataCallFailCause_t::ACCESS_BLOCK_ALL},
  {WDS_VCER_CM_IS707B_MAX_ACC_V01, DataCallFailCause_t::IS707B_MAX_ACCESS_PROBES},
  {WDS_VCER_CM_THERMAL_EMERGENCY_V01, DataCallFailCause_t::THERMAL_EMERGENCY},
  {WDS_VCER_CM_USER_CALL_ORIG_DURING_VOICE_CALL_V01, DataCallFailCause_t::CONCURRENT_SERVICES_NOT_ALLOWED},
  {WDS_VCER_CM_INCOM_REJ_V01, DataCallFailCause_t::INCOMING_CALL_REJECTED},
  {WDS_VCER_CM_NEW_NO_GW_SERV_V01, DataCallFailCause_t::NO_SERVICE_ON_GATEWAY},
  {WDS_VCER_CM_NEW_NO_GPRS_CONTEXT_V01, DataCallFailCause_t::NO_GPRS_CONTEXT},
  {WDS_VCER_CM_NEW_ILLEGAL_MS_V01, DataCallFailCause_t::ILLEGAL_MS},
  {WDS_VCER_CM_NEW_ILLEGAL_ME_V01, DataCallFailCause_t::ILLEGAL_ME},
  {WDS_VCER_CM_NEW_GPRS_SERV_AND_NON_GPRS_SERV_NOT_ALLOWED_V01, DataCallFailCause_t::GPRS_SERVICES_AND_NON_GPRS_SERVICES_NOT_ALLOWED},
  {WDS_VCER_CM_NEW_GPRS_SERV_NOT_ALLOWED_V01, DataCallFailCause_t::GPRS_SERVICES_NOT_ALLOWED},
  {WDS_VCER_CM_MS_IDENTITY_CANNOT_BE_DERIVED_BY_THE_NETWORK_V01, DataCallFailCause_t::MS_IDENTITY_CANNOT_BE_DERIVED_BY_THE_NETWORK},
  {WDS_VCER_CM_IMPLICITLY_DETACHED_V01, DataCallFailCause_t::IMPLICITLY_DETACHED},
  {WDS_VCER_CM_PLMN_NOT_ALLOWED_V01, DataCallFailCause_t::PLMN_NOT_ALLOWED},
  {WDS_VCER_CM_LA_NOT_ALLOWED_V01, DataCallFailCause_t::LOCATION_AREA_NOT_ALLOWED},
  {WDS_VCER_CM_GPRS_SERV_NOT_ALLOWED_IN_THIS_PLMN_V01, DataCallFailCause_t::GPRS_SERVICES_NOT_ALLOWED_IN_THIS_PLMN},
  {WDS_VCER_CM_PDP_DUPLICATE_V01, DataCallFailCause_t::PDP_DUPLICATE},
  {WDS_VCER_CM_UE_RAT_CHANGE_V01, DataCallFailCause_t::UE_RAT_CHANGE},
  {WDS_VCER_CM_CONGESTION_V01, DataCallFailCause_t::CONGESTION},
  {WDS_VCER_CM_NO_PDP_CONTEXT_ACTIVATED_V01, DataCallFailCause_t::NO_PDP_CONTEXT_ACTIVATED},
  {WDS_VCER_CM_ACCESS_CLASS_DSAC_REJECTION_V01, DataCallFailCause_t::ACCESS_CLASS_DSAC_REJECTION},
  {WDS_VCER_CM_PDP_ACTIVATE_MAX_RETRY_FAILED_V01, DataCallFailCause_t::PDP_ACTIVATE_MAX_RETRY_FAILED},
  {WDS_VCER_CM_RAB_FAILURE_V01, DataCallFailCause_t::RADIO_ACCESS_BEARER_FAILURE},
  {WDS_VCER_CM_ESM_UNKNOWN_EPS_BEARER_CONTEXT_V01, DataCallFailCause_t::ESM_UNKNOWN_EPS_BEARER_CONTEXT},
  {WDS_VCER_CM_DRB_RELEASED_AT_RRC_V01, DataCallFailCause_t::DRB_RELEASED_BY_RRC},
  {WDS_VCER_CM_NAS_SIG_CONN_RELEASED_V01, DataCallFailCause_t::CONNECTION_RELEASED},
  {WDS_VCER_CM_EMM_DETACHED_V01, DataCallFailCause_t::EMM_DETACHED},
  {WDS_VCER_CM_EMM_ATTACH_FAILED_V01, DataCallFailCause_t::EMM_ATTACH_FAILED},
  {WDS_VCER_CM_EMM_ATTACH_STARTED_V01, DataCallFailCause_t::EMM_ATTACH_STARTED},
  {WDS_VCER_CM_LTE_NAS_SERVICE_REQ_FAILED_V01, DataCallFailCause_t::LTE_NAS_SERVICE_REQUEST_FAILED},
  {WDS_VCER_CM_ESM_ACTIVE_DEDICATED_BEARER_REACTIVATED_BY_NW_V01, DataCallFailCause_t::DUPLICATE_BEARER_ID},
  {WDS_VCER_CM_ESM_LOWER_LAYER_FAILURE_V01, DataCallFailCause_t::ESM_COLLISION_SCENARIOS},
  {WDS_VCER_CM_ESM_SYNC_UP_WITH_NW_V01, DataCallFailCause_t::ESM_BEARER_DEACTIVATED_TO_SYNC_WITH_NETWORK},
  {WDS_VCER_CM_ESM_NW_ACTIVATED_DED_BEARER_WITH_ID_OF_DEF_BEARER_V01, DataCallFailCause_t::ESM_NW_ACTIVATED_DED_BEARER_WITH_ID_OF_DEF_BEARER},
  {WDS_VCER_CM_ESM_BAD_OTA_MESSAGE_V01, DataCallFailCause_t::ESM_BAD_OTA_MESSAGE},
  {WDS_VCER_CM_ESM_DS_REJECTED_THE_CALL_V01, DataCallFailCause_t::ESM_DOWNLOAD_SERVER_REJECTED_THE_CALL},
  {WDS_VCER_CM_ESM_CONTEXT_TRANSFERED_DUE_TO_IRAT_V01, DataCallFailCause_t::ESM_CONTEXT_TRANSFERRED_DUE_TO_IRAT},
  {WDS_VCER_CM_DS_EXPLICIT_DEACT_V01, DataCallFailCause_t::DS_EXPLICIT_DEACTIVATION},
  {WDS_VCER_CM_ESM_LOCAL_CAUSE_NONE_V01, DataCallFailCause_t::ESM_LOCAL_CAUSE_NONE},
  {WDS_VCER_CM_LTE_NAS_SERVICE_REQ_FAILED_NO_THROTTLE_V01, DataCallFailCause_t::LTE_THROTTLING_NOT_REQUIRED},
  {WDS_VCER_CM_ACL_FAILURE_V01, DataCallFailCause_t::ACCESS_CONTROL_LIST_CHECK_FAILURE},
  {WDS_VCER_CM_LTE_NAS_SERVICE_REQ_FAILED_DS_DISALLOW_V01, DataCallFailCause_t::SERVICE_NOT_ALLOWED_ON_PLMN},
  {WDS_VCER_CM_EMM_T3417_EXPIRED_V01, DataCallFailCause_t::EMM_T3417_EXPIRED},
  {WDS_VCER_CM_EMM_T3417_EXT_EXPIRED_V01, DataCallFailCause_t::EMM_T3417_EXT_EXPIRED},
  {WDS_VCER_CM_LRRC_UL_DATA_CNF_FAILURE_TXN_V01, DataCallFailCause_t::RRC_UPLINK_DATA_TRANSMISSION_FAILURE},
  {WDS_VCER_CM_LRRC_UL_DATA_CNF_FAILURE_HO_V01, DataCallFailCause_t::RRC_UPLINK_DELIVERY_FAILED_DUE_TO_HANDOVER},
  {WDS_VCER_CM_LRRC_UL_DATA_CNF_FAILURE_CONN_REL_V01, DataCallFailCause_t::RRC_UPLINK_CONNECTION_RELEASE},
  {WDS_VCER_CM_LRRC_UL_DATA_CNF_FAILURE_RLF_V01, DataCallFailCause_t::RRC_UPLINK_RADIO_LINK_FAILURE},
  {WDS_VCER_CM_LRRC_UL_DATA_CNF_FAILURE_CTRL_NOT_CONN_V01, DataCallFailCause_t::RRC_UPLINK_ERROR_REQUEST_FROM_NAS},
  {WDS_VCER_CM_LRRC_CONN_EST_FAILURE_V01, DataCallFailCause_t::RRC_CONNECTION_ACCESS_STRATUM_FAILURE},
  {WDS_VCER_CM_LRRC_CONN_EST_FAILURE_ABORTED_V01, DataCallFailCause_t::RRC_CONNECTION_ANOTHER_PROCEDURE_IN_PROGRESS},
  {WDS_VCER_CM_LRRC_CONN_EST_FAILURE_ACCESS_BARRED_V01, DataCallFailCause_t::RRC_CONNECTION_ACCESS_BARRED},
  {WDS_VCER_CM_LRRC_CONN_EST_FAILURE_CELL_RESEL_V01, DataCallFailCause_t::RRC_CONNECTION_CELL_RESELECTION},
  {WDS_VCER_CM_LRRC_CONN_EST_FAILURE_CONFIG_FAILURE_V01, DataCallFailCause_t::RRC_CONNECTION_CONFIG_FAILURE},
  {WDS_VCER_CM_LRRC_CONN_EST_FAILURE_TIMER_EXPIRED_V01, DataCallFailCause_t::RRC_CONNECTION_TIMER_EXPIRED},
  {WDS_VCER_CM_LRRC_CONN_EST_FAILURE_LINK_FAILURE_V01, DataCallFailCause_t::RRC_CONNECTION_LINK_FAILURE},
  {WDS_VCER_CM_LRRC_CONN_EST_FAILURE_NOT_CAMPED_V01, DataCallFailCause_t::RRC_CONNECTION_CELL_NOT_CAMPED},
  {WDS_VCER_CM_LRRC_CONN_EST_FAILURE_SI_FAILURE_V01, DataCallFailCause_t::RRC_CONNECTION_SYSTEM_INTERVAL_FAILURE},
  {WDS_VCER_CM_LRRC_CONN_EST_FAILURE_CONN_REJECT_V01, DataCallFailCause_t::RRC_CONNECTION_REJECT_BY_NETWORK},
  {WDS_VCER_CM_LRRC_CONN_REL_NORMAL_V01, DataCallFailCause_t::RRC_CONNECTION_NORMAL_RELEASE},
  {WDS_VCER_CM_LRRC_CONN_REL_RLF_V01, DataCallFailCause_t::RRC_CONNECTION_RADIO_LINK_FAILURE},
  {WDS_VCER_CM_LRRC_CONN_REL_CRE_FAILURE_V01, DataCallFailCause_t::RRC_CONNECTION_REESTABLISHMENT_FAILURE},
  {WDS_VCER_CM_LRRC_CONN_REL_OOS_DURING_CRE_V01, DataCallFailCause_t::RRC_CONNECTION_OUT_OF_SERVICE_DURING_CELL_REGISTER},
  {WDS_VCER_CM_LRRC_CONN_REL_ABORTED_V01, DataCallFailCause_t::RRC_CONNECTION_ABORT_REQUEST},
  {WDS_VCER_CM_LRRC_CONN_REL_SIB_READ_ERROR_V01, DataCallFailCause_t::RRC_CONNECTION_SYSTEM_INFORMATION_BLOCK_READ_ERROR},
  {WDS_VCER_CM_DETACH_WITH_REATTACH_LTE_NW_DETACH_V01, DataCallFailCause_t::NETWORK_INITIATED_DETACH_WITH_AUTO_REATTACH},
  {WDS_VCER_CM_DETACH_WITH_OUT_REATTACH_LTE_NW_DETACH_V01, DataCallFailCause_t::NETWORK_INITIATED_DETACH_NO_AUTO_REATTACH},
  {WDS_VCER_CM_ESM_PROC_TIME_OUT_V01, DataCallFailCause_t::ESM_PROCEDURE_TIME_OUT},
  {WDS_VCER_CM_INVALID_CONNECTION_ID_V01, DataCallFailCause_t::INVALID_CONNECTION_ID},
  {WDS_VCER_CM_INVALID_NSAPI_V01, DataCallFailCause_t::MAXIMIUM_NSAPIS_EXCEEDED},
  {WDS_VCER_CM_INVALID_PRI_NSAPI_V01, DataCallFailCause_t::INVALID_PRIMARY_NSAPI},
  {WDS_VCER_CM_INVALID_FIELD_V01, DataCallFailCause_t::CANNOT_ENCODE_OTA_MESSAGE},
  {WDS_VCER_CM_RAB_SETUP_FAILURE_V01, DataCallFailCause_t::RADIO_ACCESS_BEARER_SETUP_FAILURE},
  {WDS_VCER_CM_PDP_ESTABLISH_MAX_TIMEOUT_V01, DataCallFailCause_t::PDP_ESTABLISH_TIMEOUT_EXPIRED},
  {WDS_VCER_CM_PDP_MODIFY_MAX_TIMEOUT_V01, DataCallFailCause_t::PDP_MODIFY_TIMEOUT_EXPIRED},
  {WDS_VCER_CM_PDP_INACTIVE_MAX_TIMEOUT_V01, DataCallFailCause_t::PDP_INACTIVE_TIMEOUT_EXPIRED},
  {WDS_VCER_CM_PDP_LOWERLAYER_ERROR_V01, DataCallFailCause_t::PDP_LOWERLAYER_ERROR},
  {WDS_VCER_CM_PDP_MODIFY_COLLISION_V01, DataCallFailCause_t::PDP_MODIFY_COLLISION},
  {WDS_VCER_CM_MESSAGE_EXCEED_MAX_L2_LIMIT_V01, DataCallFailCause_t::MAXINUM_SIZE_OF_L2_MESSAGE_EXCEEDED},
  {WDS_VCER_CM_SM_NAS_SRV_REQ_FAILURE_V01, DataCallFailCause_t::NAS_REQUEST_REJECTED_BY_NETWORK},
  {WDS_VCER_CM_RRC_CONN_EST_FAILURE_REQ_ERROR_V01, DataCallFailCause_t::RRC_CONNECTION_INVALID_REQUEST},
  {WDS_VCER_CM_RRC_CONN_EST_FAILURE_TAI_CHANGE_V01, DataCallFailCause_t::RRC_CONNECTION_TRACKING_AREA_ID_CHANGED},
  {WDS_VCER_CM_RRC_CONN_EST_FAILURE_RF_UNAVAILABLE_V01, DataCallFailCause_t::RRC_CONNECTION_RF_UNAVAILABLE},
  {WDS_VCER_CM_RRC_CONN_REL_ABORTED_IRAT_SUCCESS_V01, DataCallFailCause_t::RRC_CONNECTION_ABORTED_DUE_TO_IRAT_CHANGE},
  {WDS_VCER_CM_RRC_CONN_REL_RLF_SEC_NOT_ACTIVE_V01, DataCallFailCause_t::RRC_CONNECTION_RELEASED_SECURITY_NOT_ACTIVE},
  {WDS_VCER_CM_RRC_CONN_REL_IRAT_TO_LTE_ABORTED_V01, DataCallFailCause_t::RRC_CONNECTION_ABORTED_AFTER_HANDOVER},
  {WDS_VCER_CM_RRC_CONN_REL_IRAT_FROM_LTE_TO_G_CCO_SUCCESS_V01, DataCallFailCause_t::RRC_CONNECTION_ABORTED_AFTER_IRAT_CELL_CHANGE},
  {WDS_VCER_CM_RRC_CONN_REL_IRAT_FROM_LTE_TO_G_CCO_ABORTED_V01, DataCallFailCause_t::RRC_CONNECTION_ABORTED_DURING_IRAT_CELL_CHANGE},
  {WDS_VCER_CM_IMSI_UNKNOWN_IN_HSS_V01, DataCallFailCause_t::IMSI_UNKNOWN_IN_HOME_SUBSCRIBER_SERVER},
  {WDS_VCER_CM_IMEI_NOT_ACCEPTED_V01, DataCallFailCause_t::IMEI_NOT_ACCEPTED},
  {WDS_VCER_CM_EPS_SERVICES_AND_NON_EPS_SERVICES_NOT_ALLOWED_V01, DataCallFailCause_t::EPS_SERVICES_AND_NON_EPS_SERVICES_NOT_ALLOWED},
  {WDS_VCER_CM_EPS_SERVICES_NOT_ALLOWED_IN_PLMN_V01, DataCallFailCause_t::EPS_SERVICES_NOT_ALLOWED_IN_PLMN},
  {WDS_VCER_CM_MSC_TEMPORARILY_NOT_REACHABLE_V01, DataCallFailCause_t::MSC_TEMPORARILY_NOT_REACHABLE},
  {WDS_VCER_CM_CS_DOMAIN_NOT_AVAILABLE_V01, DataCallFailCause_t::CS_DOMAIN_NOT_AVAILABLE},
  {WDS_VCER_CM_ESM_FAILURE_V01, DataCallFailCause_t::ESM_FAILURE},
  {WDS_VCER_CM_MAC_FAILURE_V01, DataCallFailCause_t::MAC_FAILURE},
  {WDS_VCER_CM_SYNCH_FAILURE_V01, DataCallFailCause_t::SYNCHRONIZATION_FAILURE},
  {WDS_VCER_CM_UE_SECURITY_CAPABILITIES_MISMATCH_V01, DataCallFailCause_t::UE_SECURITY_CAPABILITIES_MISMATCH},
  {WDS_VCER_CM_SECURITY_MODE_REJ_UNSPECIFIED_V01, DataCallFailCause_t::SECURITY_MODE_REJECTED},
  {WDS_VCER_CM_NON_EPS_AUTH_UNACCEPTABLE_V01, DataCallFailCause_t::UNACCEPTABLE_NON_EPS_AUTHENTICATION},
  {WDS_VCER_CM_CS_FALLBACK_CALL_EST_NOT_ALLOWED_V01, DataCallFailCause_t::CS_FALLBACK_CALL_ESTABLISHMENT_NOT_ALLOWED},
  {WDS_VCER_CM_NO_EPS_BEARER_CONTEXT_ACTIVATED_V01, DataCallFailCause_t::NO_EPS_BEARER_CONTEXT_ACTIVATED},
  {WDS_VCER_CM_EMM_INVALID_STATE_V01, DataCallFailCause_t::INVALID_EMM_STATE},
  {WDS_VCER_CM_NAS_LAYER_FAILURE_V01, DataCallFailCause_t::NAS_LAYER_FAILURE},
  {WDS_VCER_CM_MULTI_PDN_NOT_ALLOWED_V01, DataCallFailCause_t::MULTIPLE_PDP_CALL_NOT_ALLOWED},
  {WDS_VCER_CM_EMBMS_NOT_ENABLED_V01, DataCallFailCause_t::EMBMS_NOT_ENABLED},
  {WDS_VCER_CM_PENDING_REDIAL_CALL_CLEANUP_V01, DataCallFailCause_t::IRAT_HANDOVER_FAILED},
  {WDS_VCER_CM_EMBMS_REGULAR_DEACTIVATION_V01, DataCallFailCause_t::EMBMS_REGULAR_DEACTIVATION},
  {WDS_VCER_CM_TLB_REGULAR_DEACTIVATION_V01, DataCallFailCause_t::TEST_LOOPBACK_REGULAR_DEACTIVATION},
  {WDS_VCER_CM_LOWER_LAYER_REGISTRATION_FAILURE_V01, DataCallFailCause_t::LOWER_LAYER_REGISTRATION_FAILURE},
  {WDS_VCER_CM_DETACH_EPS_SERVICES_NOT_ALLOWED_V01, DataCallFailCause_t::DATA_PLAN_EXPIRED},
  {WDS_VCER_CM_SM_INTERNAL_PDP_DEACTIVATION_V01, DataCallFailCause_t::UMTS_HANDOVER_TO_IWLAN},
  {WDS_VCER_CM_CD_GEN_OR_BUSY_V01, DataCallFailCause_t::EVDO_CONNECTION_DENY_BY_GENERAL_OR_NETWORK_BUSY},
  {WDS_VCER_CM_CD_BILL_OR_AUTH_V01, DataCallFailCause_t::EVDO_CONNECTION_DENY_BY_BILLING_OR_AUTHENTICATION_FAILURE},
  {WDS_VCER_CM_CHG_HDR_V01, DataCallFailCause_t::EVDO_HDR_CHANGED},
  {WDS_VCER_CM_EXIT_HDR_V01, DataCallFailCause_t::EVDO_HDR_EXITED},
  {WDS_VCER_CM_HDR_NO_SESSION_V01, DataCallFailCause_t::EVDO_HDR_NO_SESSION},
  {WDS_VCER_CM_HDR_ORIG_DURING_GPS_FIX_V01, DataCallFailCause_t::EVDO_USING_GPS_FIX_INSTEAD_OF_HDR_CALL},
  {WDS_VCER_CM_HDR_CS_TIMEOUT_V01, DataCallFailCause_t::EVDO_HDR_CONNECTION_SETUP_TIMEOUT},
  {WDS_VCER_CM_COLLOC_ACQ_FAIL_V01, DataCallFailCause_t::FAILED_TO_ACQUIRE_COLOCATED_HDR},
  {WDS_VCER_CM_OTASP_COMMIT_IN_PROG_V01, DataCallFailCause_t::OTASP_COMMIT_IN_PROGRESS},
  {WDS_VCER_CM_NO_HYBR_HDR_SRV_V01, DataCallFailCause_t::NO_HYBRID_HDR_SERVICE},
  {WDS_VCER_CM_HDR_NO_LOCK_GRANTED_V01, DataCallFailCause_t::HDR_NO_LOCK_GRANTED},
  {WDS_VCER_CM_HOLD_OTHER_IN_PROG_V01, DataCallFailCause_t::DBM_OR_SMS_IN_PROGRESS},
  {WDS_VCER_CM_HDR_FADE_V01, DataCallFailCause_t::HDR_FADE},
  {WDS_VCER_CM_HDR_ACC_FAIL_V01, DataCallFailCause_t::HDR_ACCESS_FAILURE},
  {WDS_VCER_CM_UNSUPPORTED_1X_PREV_V01, DataCallFailCause_t::UNSUPPORTED_1X_PREV},
  {WDS_VCER_CM_CLIENT_END_V01, DataCallFailCause_t::LOCAL_END},
  {WDS_VCER_CM_NO_SRV_V01, DataCallFailCause_t::NO_SERVICE},
  {WDS_VCER_CM_FADE_V01, DataCallFailCause_t::FADE},
  {WDS_VCER_CM_REL_NORMAL_V01, DataCallFailCause_t::NORMAL_RELEASE},
  {WDS_VCER_CM_ACC_IN_PROG_V01, DataCallFailCause_t::ACCESS_ATTEMPT_ALREADY_IN_PROGRESS},
  {WDS_VCER_CM_REDIR_OR_HANDOFF_V01, DataCallFailCause_t::REDIRECTION_OR_HANDOFF_IN_PROGRESS},
  {WDS_VCER_CM_EMERGENCY_MODE_V01, DataCallFailCause_t::EMERGENCY_MODE},
  {WDS_VCER_CM_PHONE_IN_USE_V01, DataCallFailCause_t::PHONE_IN_USE},
  {WDS_VCER_CM_INVALID_MODE_V01, DataCallFailCause_t::INVALID_MODE},
  {WDS_VCER_CM_INVALID_SIM_STATE_V01, DataCallFailCause_t::INVALID_SIM_STATE},
  {WDS_VCER_CM_NO_COLLOC_HDR_V01, DataCallFailCause_t::NO_COLLOCATED_HDR},
  {WDS_VCER_CM_EMM_DETACHED_PSM_V01, DataCallFailCause_t::UE_IS_ENTERING_POWERSAVE_MODE},
  {WDS_VCER_CM_DUAL_SWITCH_V01, DataCallFailCause_t::DUAL_SWITCH},
  {WDS_VCER_CM_SM_NO_RADIO_AVAILABLE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_SM_ABORT_SERVICE_NOT_AVAILABLE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_ACC_FAIL_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_ALREADY_IN_TC_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_USER_CALL_ORIG_DURING_GPS_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_USER_CALL_ORIG_DURING_SMS_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_MC_ABORT_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_PSIST_NG_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_CALL_ORIG_THROTTLED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_CONF_FAILED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NO_GW_SERV_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NO_GPRS_CONTEXT_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_ILLEGAL_MS_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_ILLEGAL_ME_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_GPRS_SERV_AND_NON_GPRS_SERV_NOT_ALLOWED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_GPRS_SERV_NOT_ALLOWED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NEW_MS_IDENTITY_CANNOT_BE_DERIVED_BY_THE_NETWORK_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NEW_IMPLICITLY_DETACHED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NEW_PLMN_NOT_ALLOWED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NEW_LA_NOT_ALLOWED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NEW_GPRS_SERV_NOT_ALLOWED_IN_THIS_PLMN_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NEW_PDP_DUPLICATE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NEW_UE_RAT_CHANGE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NEW_CONGESTION_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NEW_NO_PDP_CONTEXT_ACTIVATED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NEW_ACCESS_CLASS_DSAC_REJECTION_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_EPS_SERVICES_NOT_ALLOWED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_TRACKING_AREA_NOT_ALLOWED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_ROAMING_NOT_ALLOWED_IN_THIS_TRACKING_AREA_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NO_SUITABLE_CELLS_IN_TRACKING_AREA_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_NOT_AUTHORIZED_FOR_THIS_CSG_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_PPD_UNKNOWN_REASON_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_PDP_MBMS_REQUEST_COLLISION_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_MBMS_DUPLICATE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_SM_PS_DETACHED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_HDR_RELEASED_BY_CM_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_OFFLINE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_CALL_CONTROL_REJECTED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_CALL_MANAGER_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_INVALID_CLASS3_APN_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_CM_MPLMN_IN_PROGRESS_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
};

unordered_map<int, DataCallFailCause_t> CallEndReason::_3gppReasonMap = {
  {WDS_VCER_3GPP_OPERATOR_DETERMINED_BARRING_V01, DataCallFailCause_t::OPERATOR_BARRED},
  {WDS_VCER_3GPP_NAS_SIGNALLING_ERROR_V01, DataCallFailCause_t::NAS_SIGNALLING},
  {WDS_VCER_3GPP_LLC_SNDCP_FAILURE_V01, DataCallFailCause_t::LLC_SNDCP},
  {WDS_VCER_3GPP_INSUFFICIENT_RESOURCES_V01, DataCallFailCause_t::INSUFFICIENT_RESOURCES},
  {WDS_VCER_3GPP_UNKNOWN_APN_V01, DataCallFailCause_t::MISSING_UKNOWN_APN},
  {WDS_VCER_3GPP_UNKNOWN_PDP_V01, DataCallFailCause_t::UNKNOWN_PDP_ADDRESS_TYPE},
  {WDS_VCER_3GPP_AUTH_FAILED_V01, DataCallFailCause_t::USER_AUTHENTICATION},
  {WDS_VCER_3GPP_GGSN_REJECT_V01, DataCallFailCause_t::ACTIVATION_REJECT_GGSN},
  {WDS_VCER_3GPP_ACTIVATION_REJECT_V01, DataCallFailCause_t::ACTIVATION_REJECT_UNSPECIFIED},
  {WDS_VCER_3GPP_OPTION_NOT_SUPPORTED_V01, DataCallFailCause_t::SERVICE_OPTION_NOT_SUPPORTED},
  {WDS_VCER_3GPP_OPTION_UNSUBSCRIBED_V01, DataCallFailCause_t::SERVICE_OPTION_NOT_SUBSCRIBED},
  {WDS_VCER_3GPP_OPTION_TEMP_OOO_V01, DataCallFailCause_t::SERVICE_OPTION_OUT_OF_ORDER},
  {WDS_VCER_3GPP_NSAPI_ALREADY_USED_V01, DataCallFailCause_t::NSAPI_IN_USE},
  {WDS_VCER_3GPP_REGULAR_DEACTIVATION_V01, DataCallFailCause_t::REGULAR_DEACTIVATION},
  {WDS_VCER_3GPP_QOS_NOT_ACCEPTED_V01, DataCallFailCause_t::QOS_NOT_ACCEPTED},
  {WDS_VCER_3GPP_NETWORK_FAILURE_V01, DataCallFailCause_t::NETWORK_FAILURE},
  {WDS_VCER_3GPP_UMTS_REACTIVATION_REQ_V01, DataCallFailCause_t::UMTS_REACTIVATION_REQ},
  {WDS_VCER_3GPP_FEATURE_NOT_SUPP_V01, DataCallFailCause_t::FEATURE_NOT_SUPP},
  {WDS_VCER_3GPP_TFT_SEMANTIC_ERROR_V01, DataCallFailCause_t::TFT_SEMANTIC_ERROR},
  {WDS_VCER_3GPP_TFT_SYTAX_ERROR_V01, DataCallFailCause_t::TFT_SYTAX_ERROR},
  {WDS_VCER_3GPP_UNKNOWN_PDP_CONTEXT_V01, DataCallFailCause_t::UNKNOWN_PDP_CONTEXT},
  {WDS_VCER_3GPP_FILTER_SEMANTIC_ERROR_V01, DataCallFailCause_t::FILTER_SEMANTIC_ERROR},
  {WDS_VCER_3GPP_FILTER_SYTAX_ERROR_V01, DataCallFailCause_t::FILTER_SYTAX_ERROR},
  {WDS_VCER_3GPP_PDP_WITHOUT_ACTIVE_TFT_V01, DataCallFailCause_t::PDP_WITHOUT_ACTIVE_TFT},
  {WDS_VCER_3GPP_ACTIVATION_REJECTED_BCM_VIOLATION_V01, DataCallFailCause_t::ACTIVATION_REJECTED_BCM_VIOLATION},
  {WDS_VCER_3GPP_IP_V4_ONLY_ALLOWED_V01, DataCallFailCause_t::ONLY_IPV4_ALLOWED},
  {WDS_VCER_3GPP_IP_V6_ONLY_ALLOWED_V01, DataCallFailCause_t::ONLY_IPV6_ALLOWED},
  {WDS_VCER_3GPP_SINGLE_ADDR_BEARER_ONLY_V01, DataCallFailCause_t::ONLY_SINGLE_BEARER_ALLOWED},
  {WDS_VCER_3GPP_ESM_INFO_NOT_RECEIVED_V01, DataCallFailCause_t::ESM_INFO_NOT_RECEIVED},
  {WDS_VCER_3GPP_PDN_CONN_DOES_NOT_EXIST_V01, DataCallFailCause_t::PDN_CONN_DOES_NOT_EXIST},
  {WDS_VCER_3GPP_MULTI_CONN_TO_SAME_PDN_NOT_ALLOWED_V01, DataCallFailCause_t::MULTI_CONN_TO_SAME_PDN_NOT_ALLOWED},
  {WDS_VCER_3GPP_COLLISION_WITH_NW_INIT_REQ_V01, DataCallFailCause_t::COLLISION_WITH_NETWORK_INITIATED_REQUEST},
  {WDS_VCER_3GPP_IP_V4V6_ONLY_ALLOWED_V01, DataCallFailCause_t::ONLY_IPV4V6_ALLOWED},
  {WDS_VCER_3GPP_NON_IP_ONLY_ALLOWED_V01, DataCallFailCause_t::ONLY_NON_IP_ALLOWED},
  {WDS_VCER_3GPP_UNSUPPORTED_QCI_VALUE_V01, DataCallFailCause_t::UNSUPPORTED_QCI_VALUE},
  {WDS_VCER_3GPP_BEARER_HANDLING_NOT_SUPPORTED_V01, DataCallFailCause_t::BEARER_HANDLING_NOT_SUPPORTED},
  {WDS_VCER_3GPP_MAX_ACTIVE_PDP_CONTEXT_REACHED_V01, DataCallFailCause_t::MAX_ACTIVE_PDP_CONTEXT_REACHED},
  {WDS_VCER_3GPP_UNSUPPORTED_APN_IN_CURRENT_PLMN_V01, DataCallFailCause_t::UNSUPPORTED_APN_IN_CURRENT_PLMN},
  {WDS_VCER_3GPP_INVALID_TRANSACTION_ID_V01, DataCallFailCause_t::INVALID_TRANSACTION_ID},
  {WDS_VCER_3GPP_MESSAGE_INCORRECT_SEMANTIC_V01, DataCallFailCause_t::MESSAGE_INCORRECT_SEMANTIC},
  {WDS_VCER_3GPP_INVALID_MANDATORY_INFO_V01, DataCallFailCause_t::INVALID_MANDATORY_INFO},
  {WDS_VCER_3GPP_MESSAGE_TYPE_UNSUPPORTED_V01, DataCallFailCause_t::MESSAGE_TYPE_UNSUPPORTED},
  {WDS_VCER_3GPP_MSG_TYPE_NONCOMPATIBLE_STATE_V01, DataCallFailCause_t::MSG_TYPE_NONCOMPATIBLE_STATE},
  {WDS_VCER_3GPP_UNKNOWN_INFO_ELEMENT_V01, DataCallFailCause_t::UNKNOWN_INFO_ELEMENT},
  {WDS_VCER_3GPP_CONDITIONAL_IE_ERROR_V01, DataCallFailCause_t::CONDITIONAL_IE_ERROR},
  {WDS_VCER_3GPP_MSG_AND_PROTOCOL_STATE_UNCOMPATIBLE_V01, DataCallFailCause_t::MSG_AND_PROTOCOL_STATE_UNCOMPATIBLE},
  {WDS_VCER_3GPP_PROTOCOL_ERROR_V01, DataCallFailCause_t::PROTOCOL_ERRORS},
  {WDS_VCER_3GPP_APN_TYPE_CONFLICT_V01, DataCallFailCause_t::APN_TYPE_CONFLICT},
  {WDS_VCER_3GPP_INVALID_PCSCF_ADDR_V01, DataCallFailCause_t::INVALID_PCSCF_ADDR},
  {WDS_VCER_3GPP_INTERNAL_CALL_PREEMPT_BY_HIGH_PRIO_APN_V01, DataCallFailCause_t::INTERNAL_CALL_PREEMPT_BY_HIGH_PRIO_APN},
  {WDS_VCER_3GPP_EMM_ACCESS_BARRED_V01, DataCallFailCause_t::EMM_ACCESS_BARRED},
  {WDS_VCER_3GPP_EMERGENCY_IFACE_ONLY_V01, DataCallFailCause_t::EMERGENCY_IFACE_ONLY},
  {WDS_VCER_3GPP_IFACE_MISMATCH_V01, DataCallFailCause_t::IFACE_MISMATCH},
  {WDS_VCER_3GPP_COMPANION_IFACE_IN_USE_V01, DataCallFailCause_t::COMPANION_IFACE_IN_USE},
  {WDS_VCER_3GPP_IP_ADDRESS_MISMATCH_V01, DataCallFailCause_t::IP_ADDRESS_MISMATCH},
  {WDS_VCER_3GPP_IFACE_AND_POL_FAMILY_MISMATCH_V01, DataCallFailCause_t::IFACE_AND_POL_FAMILY_MISMATCH},
  {WDS_VCER_3GPP_EMM_ACCESS_BARRED_INFINITE_RETRY_V01, DataCallFailCause_t::EMM_ACCESS_BARRED_INFINITE_RETRY},
  {WDS_VCER_3GPP_AUTH_FAILURE_ON_EMERGENCY_CALL_V01, DataCallFailCause_t::AUTH_FAILURE_ON_EMERGENCY_CALL},
  {WDS_VCER_3GPP_INVALID_DNS_ADDR_V01, DataCallFailCause_t::INVALID_DNS_ADDR},
  {WDS_VCER_3GPP_PTI_MISMATCH_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_3GPP_TEST_LOOPBACK_MODE_A_OR_B_ENABLED_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_3GPP_EMM_ACCESS_BARRED_EAB_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_3GPP_INVALID_PCSCF_DNS_ADDR_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_3GPP_CALL_PREEMPT_BY_EMERGENCY_APN_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_3GPP_UE_INIT_DETACH_OR_DISCONNECT_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
};

unordered_map<int, DataCallFailCause_t> CallEndReason::pppReasonMap = {
  {WDS_VCER_PPP_TIMEOUT_V01, DataCallFailCause_t::PPP_TIMEOUT},
  {WDS_VCER_PPP_AUTH_FAILURE_V01, DataCallFailCause_t::PPP_AUTH_FAILURE},
  {WDS_VCER_PPP_OPTION_MISMATCH_V01, DataCallFailCause_t::PPP_OPTION_MISMATCH},
  {WDS_VCER_PPP_PAP_FAILURE_V01, DataCallFailCause_t::PPP_PAP_FAILURE},
  {WDS_VCER_PPP_CHAP_FAILURE_V01, DataCallFailCause_t::PPP_CHAP_FAILURE},
  {WDS_VCER_PPP_ERR_CLOSE_IN_PROGRESS_V01, DataCallFailCause_t::PPP_CLOSE_IN_PROGRESS},
  {WDS_VCER_PPPNV_REFRESH_IN_PROGRESS_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
  {WDS_VCER_PPP_UNKNOWN_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
};

unordered_map<int, DataCallFailCause_t> CallEndReason::ehrpdReasonMap = {
  {WDS_VCER_EHRPD_SUBS_LIMITED_TO_V4_V01, DataCallFailCause_t::LIMITED_TO_IPV4},
  {WDS_VCER_EHRPD_SUBS_LIMITED_TO_V6_V01, DataCallFailCause_t::LIMITED_TO_IPV6},
  {WDS_VCER_EHRPD_VSNCP_TIMEOUT_V01, DataCallFailCause_t::VSNCP_TIMEOUT},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_GEN_ERROR_V01, DataCallFailCause_t::VSNCP_GEN_ERROR},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_UNAUTH_APN_V01, DataCallFailCause_t::VSNCP_APN_UNATHORIZED},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_PDN_LIMIT_EXCEED_V01, DataCallFailCause_t::VSNCP_PDN_LIMIT_EXCEEDED},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_NO_PDN_GW_V01, DataCallFailCause_t::VSNCP_NO_PDN_GATEWAY_ADDRESS},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_PDN_GW_UNREACH_V01, DataCallFailCause_t::VSNCP_PDN_GATEWAY_UNREACHABLE},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_PDN_GW_REJ_V01, DataCallFailCause_t::VSNCP_PDN_GATEWAY_REJECT},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_INSUFF_PARAM_V01, DataCallFailCause_t::VSNCP_INSUFFICIENT_PARAMETERS},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_RESOURCE_UNAVAIL_V01, DataCallFailCause_t::VSNCP_RESOURCE_UNAVAILABLE},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_ADMIN_PROHIBIT_V01, DataCallFailCause_t::VSNCP_ADMINISTRATIVELY_PROHIBITED},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_PDN_ID_IN_USE_V01, DataCallFailCause_t::VSNCP_PDN_ID_IN_USE},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_SUBSCR_LIMITATION_V01, DataCallFailCause_t::VSNCP_SUBSCRIBER_LIMITATION},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_PDN_EXISTS_FOR_THIS_APN_V01, DataCallFailCause_t::VSNCP_PDN_EXISTS_FOR_THIS_APN},
  {WDS_VCER_EHRPD_VSNCP_3GPP2I_RECONNECT_NOT_ALLOWED_V01, DataCallFailCause_t::VSNCP_RECONNECT_NOT_ALLOWED},
  {WDS_VCER_EHRPD_VSNCP_FAILURE_V01, DataCallFailCause_t::ERROR_UNSPECIFIED},
};

unordered_map<int, DataCallFailCause_t> CallEndReason::ipv6ReasonMap = {
  {WDS_VCER_IPV6_PREFIX_UNAVAILABLE_V01, DataCallFailCause_t::IPV6_PREFIX_UNAVAILABLE},
  {WDS_VCER_IPV6_ERR_HRPD_IPV6_DISABLED_V01, DataCallFailCause_t::PROTOCOL_ERRORS},
  {WDS_VCER_IPV6_DISABLED_V01, DataCallFailCause_t::ONLY_IPV4_ALLOWED},
};

unordered_map<int, DataCallFailCause_t> CallEndReason::handoffReasonMap = {
  {WDS_VCER_HANDOFF_PREF_SYS_BACK_TO_SRAT_V01, DataCallFailCause_t::HANDOFF_PREFERENCE_CHANGED},
};

unordered_map<int, DataCallFailCause_t> CallEndReason::apAssistHandoffReasonMap = {
  {static_cast<int>(ApAssistHandoverFailCause_t::NONE), DataCallFailCause_t::NONE},
  {static_cast<int>(ApAssistHandoverFailCause_t::TIMEOUT), DataCallFailCause_t::ERROR_UNSPECIFIED},
  {static_cast<int>(ApAssistHandoverFailCause_t::APN_PREF_SYSTEM_CHANGE_REQUEST_FAILURE), DataCallFailCause_t::HANDOFF_PREFERENCE_CHANGED},
  {static_cast<int>(ApAssistHandoverFailCause_t::HANDOFF_FAILURE), DataCallFailCause_t::HANDOFF_PREFERENCE_CHANGED},
};

unordered_map<dsi_ce_reason_type_t, unordered_map<int, DataCallFailCause_t>> CallEndReason::callEndReasonTypeMap = {
  {DSI_CE_TYPE_MOBILE_IP, mipReasonMap},
  {DSI_CE_TYPE_INTERNAL, internalReasonMap},
  {DSI_CE_TYPE_CALL_MANAGER_DEFINED, cmReasonMap},
  {DSI_CE_TYPE_3GPP_SPEC_DEFINED, _3gppReasonMap},
  {DSI_CE_TYPE_PPP, pppReasonMap},
  {DSI_CE_TYPE_EHRPD, ehrpdReasonMap},
  {DSI_CE_TYPE_IPV6, ipv6ReasonMap},
  {static_cast<dsi_ce_reason_type_t>(CallEndReason::AP_ASSIST_HANDOVER), apAssistHandoffReasonMap},
};

DataCallFailCause_t CallEndReason::getCallEndReason(dsi_ce_reason_t dsiReason) {
  dsi_ce_reason_type_t reasonType = dsiReason.reason_type;
  int reasonCode = dsiReason.reason_code;
  if (callEndReasonTypeMap.find(reasonType) == callEndReasonTypeMap.end()) {
    Log::getInstance().d("[CallEndReason]: getCallEndReason type unknown");
    return DataCallFailCause_t::ERROR_UNSPECIFIED;
  }
  if (callEndReasonTypeMap[reasonType].find(reasonCode) == callEndReasonTypeMap[reasonType].end()) {
    Log::getInstance().d("[CallEndReason]: getCallEndReason code unknown");
    return DataCallFailCause_t::ERROR_UNSPECIFIED;
  }
  return callEndReasonTypeMap[reasonType][reasonCode];
}

bool CallEndReason::isPermanentFailure(DataCallFailCause_t rilReason) {
  bool retVal = false;
  switch (rilReason) {
    case DataCallFailCause_t::SERVICE_OPTION_NOT_SUPPORTED:
    case DataCallFailCause_t::DUN_CALL_DISALLOWED:
    case DataCallFailCause_t::SERVICE_OPTION_NOT_SUBSCRIBED:
    case DataCallFailCause_t::NSAPI_IN_USE:
    case DataCallFailCause_t::ONLY_IPV4_ALLOWED:
    case DataCallFailCause_t::PDN_IPV6_CALL_DISALLOWED:
    case DataCallFailCause_t::ONLY_IPV6_ALLOWED:
    case DataCallFailCause_t::PDN_IPV4_CALL_DISALLOWED:
    case DataCallFailCause_t::PROTOCOL_ERRORS:
    case DataCallFailCause_t::MISSING_UKNOWN_APN:
    case DataCallFailCause_t::APN_DISABLED:
    case DataCallFailCause_t::UNKNOWN_PDP_ADDRESS_TYPE:
    case DataCallFailCause_t::IP_VERSION_MISMATCH:
      retVal = true;
      break;
    default:
      retVal = false;
      break;
  }
  std::ostringstream ss;
  ss << std::boolalpha << "[CallInfo]: isPermanentFailure=" << retVal <<
      ", rilReason=" << (int)rilReason;
  Log::getInstance().d(ss.str());
  return retVal;
}

void CallInfo::dump(string padding, ostream& os) const {
  os << padding << "cid: " << cid << endl;
  os << padding << "active: " << (int)active << endl;
  os << padding << "dormantState: " << std::boolalpha << dormantState << endl;
  os << padding << "v4Connected: " << std::boolalpha << v4Connected << endl;
  os << padding << "v6Connected: " << std::boolalpha << v6Connected << endl;
  os << padding << "v4HandedOver: " << (int)v4HandedOver << endl;
  os << padding << "v6HandedOver: " << (int)v6HandedOver << endl;
  os << padding << "intentToChangeInProgress: " << std::boolalpha << intentToChangeInProgress << endl;
  os << padding << "thirdPartyHOParamsSet: " << std::boolalpha << thirdPartyHOParamsSet << endl;
  os << padding << "fallbackInProgress: " << std::boolalpha << fallbackInProgress << endl;
  os << padding << "isEmbmsCall: " << std::boolalpha << isEmbmsCall << endl;
  os << padding << "pendingAck: " << std::boolalpha << pendingAck << endl;
  os << padding << "callBringUpCapability: " << (int)callBringUpCapability << endl;
  os << padding << "currentRAT: " << (int)currentRAT << endl;
  os << padding << "preferredRAT: " << (int)preferredRAT << endl;
  os << padding << "radioRAT: " << radioRAT << endl;
  os << padding << "transportType: " << transportType << endl;
  os << padding << "deviceName: " << deviceName << endl;
  os << padding << "ipAddresses: " << ipAddresses << endl;
  os << padding << "gatewayAddresses: " << gatewayAddresses << endl;
  os << padding << "dnsAddresses: " << dnsAddresses << endl;
  os << padding << "pcscfAddresses: " << pcscfAddresses << endl;
  os << padding << "ipType: " << ipType << endl;
  os << padding << "mtu: " << mtu << endl;
  os << padding << "mtuV4: " << mtuV4 << endl;
  os << padding << "mtuV6: " << mtuV6 << endl;
  os << padding << "callParamsChanged: " << std::boolalpha << callParamsChanged << endl;
  os << padding << "dsiHandle: " << (void *)dsiHandle << endl;
  os << padding << "request: " << (request == nullptr ? "null" : request->dump()) << endl;
  os << padding << "bearers: ";
  for (auto bearer : bearerCollection.bearers) {
    bearer.dump("", os);
    os << ",";
  }
  os << endl;
  os << padding << "profileInfo:" << endl;
  if (profileInfo != nullptr) {
    profileInfo->dump(padding + "    ", os);
  }
}
