/*
 * Copyright (c) 2020 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"
#include "IOpener.hpp"

/** @file  IOpener.idl */

/** @cond */

/** 0 is not a valid service ID. */

class IOpenerImplBase : protected ImplBase, public IIOpener {
   public:
    IOpenerImplBase() {}
    virtual ~IOpenerImplBase() {}

    virtual int32_t invoke(ObjectOp op, ObjectArg* a, ObjectCounts k) {
        switch (ObjectOp_methodID(op)) {
            case OP_open: {
                if (k != ObjectCounts_pack(1, 0, 0, 1) ||
                    a[0].b.size != 4) {
                    break;
                }
                const uint32_t* id_ptr = (const uint32_t*) a[0].b.ptr;
                return open(*id_ptr, &a[1].o);
            }
            default: { return Object_ERROR_INVALID; }
        }
        return Object_ERROR_INVALID;
    }
};

