/*
 * Copyright (c) 2020 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"

/** @file  types.idl */

struct TUIConfig {
    /*
     * @brief  Enable/Disable use of Secure Indicator.
     **/
    uint8_t useSecureIndicator;
    /*
     * @brief  String identifier for the layout to be displayed on the screen.
     **/
    uint8_t layoutName[256];
    /*
     * @brief Enable Session Authentication
     **/
    uint8_t enableSessionAuth;
};

static const uint32_t TUI_PRIMARY_DISPLAY = UINT32_C(1);
static const uint32_t TUI_SECONDARY_DISPLAY = UINT32_C(2);

static const uint32_t TUI_TOUCH_INPUT = UINT32_C(1);
static const uint32_t TUI_MAX_INPUT = UINT32_C(1);

