/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.5 at Tue Oct 27 14:27:29 2020. */

#include "qsh_wifi.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t qsh_wifi_ranging_req_ap_num_frames_per_burst_default = 8u;


const pb_field_t qsh_wifi_cmd_open_fields[3] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, qsh_wifi_cmd_open, get_capability, get_capability, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, qsh_wifi_cmd_open, get_version, get_capability, 0),
    PB_LAST_FIELD
};

const pb_field_t qsh_wifi_cmd_ack_fields[5] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, qsh_wifi_cmd_ack, status, status, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, qsh_wifi_cmd_ack, command, status, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_cmd_ack, version, command, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_cmd_ack, capabilities, version, 0),
    PB_LAST_FIELD
};

const pb_field_t qsh_wifi_cmd_scan_req_fields[7] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, qsh_wifi_cmd_scan_req, scan_type, scan_type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_cmd_scan_req, max_scan_age_ms, scan_type, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, qsh_wifi_cmd_scan_req, band, max_scan_age_ms, 0),
    PB_FIELD(  4, UINT32  , REPEATED, CALLBACK, OTHER, qsh_wifi_cmd_scan_req, freq_list, band, 0),
    PB_FIELD(  5, STRING  , REPEATED, CALLBACK, OTHER, qsh_wifi_cmd_scan_req, ssid_list, freq_list, 0),
    PB_FIELD(  6, UENUM   , OPTIONAL, STATIC  , OTHER, qsh_wifi_cmd_scan_req, radio_chain_pref, ssid_list, 0),
    PB_LAST_FIELD
};

const pb_field_t qsh_wifi_bss_info_fields[16] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, qsh_wifi_bss_info, bssid, bssid, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_bss_info, age_ms, bssid, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, qsh_wifi_bss_info, capability_info, age_ms, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, qsh_wifi_bss_info, ssid, capability_info, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_bss_info, flags, ssid, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, qsh_wifi_bss_info, rssi, flags, 0),
    PB_FIELD(  7, UENUM   , REQUIRED, STATIC  , OTHER, qsh_wifi_bss_info, band, rssi, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, qsh_wifi_bss_info, freq, band, 0),
    PB_FIELD(  9, UINT32  , REQUIRED, STATIC  , OTHER, qsh_wifi_bss_info, channel_width, freq, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_bss_info, cent_freq0, channel_width, 0),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_bss_info, cent_freq1, cent_freq0, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_bss_info, security_mode, cent_freq1, 0),
    PB_FIELD( 13, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_bss_info, radio_chain, security_mode, 0),
    PB_FIELD( 14, INT32   , OPTIONAL, STATIC  , OTHER, qsh_wifi_bss_info, rssi_chain0, radio_chain, 0),
    PB_FIELD( 15, INT32   , OPTIONAL, STATIC  , OTHER, qsh_wifi_bss_info, rssi_chain1, rssi_chain0, 0),
    PB_LAST_FIELD
};

const pb_field_t qsh_wifi_evt_scan_result_fields[10] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, qsh_wifi_evt_scan_result, status, status, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, qsh_wifi_evt_scan_result, result_total, status, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, qsh_wifi_evt_scan_result, result_count, result_total, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, qsh_wifi_evt_scan_result, last_in_series, result_count, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_evt_scan_result, scan_type, last_in_series, 0),
    PB_FIELD(  6, UINT64  , OPTIONAL, STATIC  , OTHER, qsh_wifi_evt_scan_result, ref_time, scan_type, 0),
    PB_FIELD(  7, UINT32  , REPEATED, CALLBACK, OTHER, qsh_wifi_evt_scan_result, scanned_freq_list, ref_time, 0),
    PB_FIELD(  8, MESSAGE , REPEATED, CALLBACK, OTHER, qsh_wifi_evt_scan_result, ap_list, scanned_freq_list, &qsh_wifi_bss_info_fields),
    PB_FIELD( 10, UENUM   , OPTIONAL, STATIC  , OTHER, qsh_wifi_evt_scan_result, radio_chain_pref, ap_list, 0),
    PB_LAST_FIELD
};

const pb_field_t qsh_wifi_cmd_monitor_req_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, qsh_wifi_cmd_monitor_req, action, action, 0),
    PB_LAST_FIELD
};

const pb_field_t qsh_wifi_cmd_ranging_req_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, qsh_wifi_cmd_ranging_req, bss_list, bss_list, &qsh_wifi_ranging_req_ap_fields),
    PB_LAST_FIELD
};

const pb_field_t qsh_wifi_ranging_req_ap_fields[8] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, qsh_wifi_ranging_req_ap, mac_addr, mac_addr, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, qsh_wifi_ranging_req_ap, freq, mac_addr, 0),
    PB_FIELD(  3, UENUM   , REQUIRED, STATIC  , OTHER, qsh_wifi_ranging_req_ap, channel_width, freq, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_req_ap, cent_freq0, channel_width, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_req_ap, cent_freq1, cent_freq0, 0),
    PB_FIELD(  6, BOOL    , REQUIRED, STATIC  , OTHER, qsh_wifi_ranging_req_ap, request_lci, cent_freq1, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, qsh_wifi_ranging_req_ap, num_frames_per_burst, request_lci, &qsh_wifi_ranging_req_ap_num_frames_per_burst_default),
    PB_LAST_FIELD
};

const pb_field_t qsh_wifi_evt_ranging_result_fields[6] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, qsh_wifi_evt_ranging_result, status, status, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, qsh_wifi_evt_ranging_result, result_total, status, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, qsh_wifi_evt_ranging_result, result_count, result_total, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, qsh_wifi_evt_ranging_result, last_in_series, result_count, 0),
    PB_FIELD(  5, MESSAGE , REPEATED, CALLBACK, OTHER, qsh_wifi_evt_ranging_result, bss_list, last_in_series, &qsh_wifi_ranging_result_ap_fields),
    PB_LAST_FIELD
};

const pb_field_t qsh_wifi_ranging_result_ap_fields[15] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, qsh_wifi_ranging_result_ap, mac_addr, mac_addr, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, qsh_wifi_ranging_result_ap, rtt_status, mac_addr, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, qsh_wifi_ranging_result_ap, result_flag, rtt_status, 0),
    PB_FIELD(  4, UINT64  , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_result_ap, timestamp, result_flag, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_result_ap, rssi, timestamp, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_result_ap, distance, rssi, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_result_ap, distance_stddev, distance, 0),
    PB_FIELD(  8, INT64   , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_result_ap, latitude, distance_stddev, 0),
    PB_FIELD(  9, INT64   , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_result_ap, longitude, latitude, 0),
    PB_FIELD( 10, INT32   , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_result_ap, altitude, longitude, 0),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_result_ap, latitude_uncertainty, altitude, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_result_ap, longitude_uncertainty, latitude_uncertainty, 0),
    PB_FIELD( 13, UENUM   , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_result_ap, altitude_type, longitude_uncertainty, 0),
    PB_FIELD( 14, UINT32  , OPTIONAL, STATIC  , OTHER, qsh_wifi_ranging_result_ap, altitude_uncertainty, altitude_type, 0),
    PB_LAST_FIELD
};
















/* @@protoc_insertion_point(eof) */
