/*
* Copyright (c) 2020 Qualcomm Technologies, Inc.
* All Rights Reserved.
* Confidential and Proprietary - Qualcomm Technologies, Inc.
*/
/**
* @addtogroup CAppClient
* @{
  Class CAppClient implements \link IAppClient \endlink interface.
  This class provides an interface to obtain app-provided functionalities.

  The class ID `AppClient` is not included in the default privilege set.
*/
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CAppClient_UID UINT32_C(0x97)
