/*****************************************************************************
  Copyright (c) 2021 Qualcomm Technologies, Inc.
  All rights reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.
*****************************************************************************/

/**
* @addtogroup CQWESTAServices
* @{
   Class CQWESTAServices implements \link IQWESTAServices \endlink interface.
 
   The class ID `QWESTAServices` is not included in the default privilege set.
   It needs to be added to the privileges section in the metadata to allow the
   TA to use the CQWESTAServices class.
 */
 #pragma once
 // AUTOGENERATED FILE: DO NOT EDIT
 
 #include <stdint.h>
 #include "object.h"
 
 #define CQWESTAServices_UID UINT32_C(120)
 
